title: "My Annotated Novel"
description: "An example with pop-up annotations using Jekyll and GitHub Pages"
theme: minima

markdown: kramdown
highlighter: rouge

# Optional: some common plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
